name: codetrack
description: All your coding profiles, contests & flashcards in one place.
publish_to: "none"
version: 0.2.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  http: ^1.2.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
